options:
  slurmdbd_pid_file:
    type: string
    default: /var/run/slurm-llnl/slurmdbd.pid
    description: >-
      'Fully qualified pathname of a file into which the slurmctld daemon may
      write its process id. This may be used for automated signal processing.
      The default value is "/var/run/slurmdbd.pid".'
  slurmdbd_port:
    type: int
    default: 6817
    description: >-
      'The port number that the Slurm dbd, slurmdbd listens to.'
  slurm_user:
    type: string
    default: slurm
    description: >-
      The name of the user that the slurmdbd daemon executes as. For security
      purposes, a user other than "root" is recommended.
  storage_user:
    type: string
    default: slurm
    description: >-
      The name of the user that that will be passed to a storage backend for
      future authentication.
  storage_loc:
    type: string
    default: slurm_acct_db
    description: >-
      The name of the database to be created in a storage backend.
  slurmdbd_debug:
    type: string
    default: info
    description: >-
      "The level of detail to provide slurmdbd daemon's logs. The default value
      is info. If the slurmdbd daemon is initiated with -v or --verbose
      options, that debug level will be preserve or restored upon
      reconfiguration."
  slurmdbd_log_file:
    type: string
    default: /var/log/slurm-llnl/slurmdbd.log
    description: >-
      "Fully qualified pathname of a file into which the slurmcdbd daemon's logs
      are written. The default value is none (performs logging via syslog)."
  slurmdbd_debug:
    type: string
    default: info
    description: >-
      "The level of detail to provide slurmd daemon's logs. The default value is
      info."
      # TODO:
      #  config_flags:
      #    type: string
      #    default:
      #    description: >-
      #      User-provided slurmdbd configuration. Should be used to configure options
      #      not present in the charm like Purge* and Arhive* options.
